definitions:
  dtos.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  dtos.ImageMetadataResponse:
    properties:
      copyright:
        type: string
      date:
        type: string
      explanation:
        type: string
      title:
        type: string
      url:
        type: string
    type: object
info:
  contact: {}
  description: Сервис предоставляет возможность получения "a picture of the day" и
    его метаданные
  title: APOD API
  version: "1.0"
paths:
  /api/apod/:
    get:
      description: Позволяет получить метаданные всех доступных изображений
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/dtos.ImageMetadataResponse'
            type: array
        "500":
          description: Если мы не можем получить изображение(я) из хранилища или в
            случае других непредвиденных проблем
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: Получение метаданных всех доступных изображений
      tags:
      - data
  /api/apod/{date}:
    get:
      description: Позволяет получить метаданные изображения согласно переданной дате
      parameters:
      - description: Дата в формате YYYY-MM-DD
        in: path
        name: date
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dtos.ImageMetadataResponse'
        "400":
          description: 'Если в качестве параметра передана неправильная дата или она
            не в формате YYYY-MM-DD. Сообщение: invalid_date'
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "404":
          description: 'Если метаданные по переданной дате отсутствуют. Сообщение:
            not_found'
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
        "500":
          description: Если мы не можем получить изображение из хранилища или в случае
            других непредвиденных проблем
          schema:
            $ref: '#/definitions/dtos.ErrorResponse'
      summary: Получение метаданных изображения
      tags:
      - data
swagger: "2.0"
